/* Auto-generated by vkso-gen-types (safe funcs only). */
#pragma once
#include <stddef.h>
#include <stdint.h>

/* --- BTF source: zlib_lkm (/sys/kernel/btf/zlib_lkm) --- */
/* --- typedef Bytef --- */
typedef Byte Bytef;

/* --- typedef voidpf --- */
typedef void *voidpf;

/* --- typedef z_crc_t --- */
typedef u32 z_crc_t;

/* --- typedef alloc_func --- */
typedef voidpf (*alloc_func)(voidpf, uInt, uInt);

/* --- typedef free_func --- */
typedef void (*free_func)(voidpf, voidpf);

/* --- struct z_stream_s --- */
struct z_stream_s {
	const Bytef *next_in;
	uInt avail_in;
	uLong total_in;
	Bytef *next_out;
	uInt avail_out;
	uLong total_out;
	const char *msg;
	struct internal_state *state;
	alloc_func zalloc;
	free_func zfree;
	voidpf opaque;
	int data_type;
	uLong adler;
	uLong reserved;
};

/* --- typedef z_stream --- */
typedef struct z_stream_s z_stream;

/* --- typedef z_streamp --- */
typedef z_stream *z_streamp;

/* --- typedef gz_header --- */
typedef struct gz_header_s gz_header;

/* --- typedef gz_headerp --- */
typedef gz_header *gz_headerp;

/* --- typedef Posf --- */
typedef Pos Posf;

/* --- typedef static_tree_desc --- */
typedef struct static_tree_desc_s static_tree_desc;

/* --- struct tree_desc_s --- */
struct tree_desc_s {
	ct_data *dyn_tree;
	int max_code;
	const static_tree_desc *stat_desc;
};

/* --- typedef uchf --- */
typedef uch uchf;

/* --- typedef ushf --- */
typedef ush ushf;

/* --- struct internal_state --- */
struct internal_state {
	z_streamp strm;
	int status;
	Bytef *pending_buf;
	ulg pending_buf_size;
	Bytef *pending_out;
	ulg pending;
	int wrap;
	gz_headerp gzhead;
	ulg gzindex;
	Byte method;
	int last_flush;
	uInt w_size;
	uInt w_bits;
	uInt w_mask;
	Bytef *window;
	ulg window_size;
	Posf *prev;
	Posf *head;
	uInt ins_h;
	uInt hash_size;
	uInt hash_bits;
	uInt hash_mask;
	uInt hash_shift;
	long int block_start;
	uInt match_length;
	IPos prev_match;
	int match_available;
	uInt strstart;
	uInt match_start;
	uInt lookahead;
	uInt prev_length;
	uInt max_chain_length;
	uInt max_lazy_match;
	int level;
	int strategy;
	uInt good_match;
	int nice_match;
	struct ct_data_s dyn_ltree[573];
	struct ct_data_s dyn_dtree[61];
	struct ct_data_s bl_tree[39];
	struct tree_desc_s l_desc;
	struct tree_desc_s d_desc;
	struct tree_desc_s bl_desc;
	ush bl_count[16];
	int heap[573];
	int heap_len;
	int heap_max;
	uch depth[573];
	uchf *l_buf;
	uInt lit_bufsize;
	uInt last_lit;
	ushf *d_buf;
	ulg opt_len;
	ulg static_len;
	uInt matches;
	uInt insert;
	ush bi_buf;
	int bi_valid;
	ulg high_water;
};

/* --- struct gz_header_s --- */
struct gz_header_s {
	int text;
	uLong time;
	int xflags;
	int os;
	Bytef *extra;
	uInt extra_len;
	uInt extra_max;
	Bytef *name;
	uInt name_max;
	Bytef *comment;
	uInt comm_max;
	int hcrc;
	int done;
};

/* --- typedef intf --- */
typedef int intf;

/* --- struct static_tree_desc_s --- */
struct static_tree_desc_s {
	const ct_data *static_tree;
	const intf *extra_bits;
	int extra_base;
	int elems;
	int max_length;
};

/* --- BTF source: vmlinux (/sys/kernel/btf/vmlinux) --- */
/* --- typedef __u32 --- */
typedef unsigned int __u32;

/* --- typedef u32 --- */
typedef __u32 u32;

/* --- typedef Byte --- */
typedef unsigned char Byte;

/* --- typedef uLong --- */
typedef long unsigned int uLong;

/* --- typedef uInt --- */
typedef unsigned int uInt;

/* --- typedef uch --- */
typedef unsigned char uch;

/* --- typedef ush --- */
typedef short unsigned int ush;

/* --- typedef ulg --- */
typedef long unsigned int ulg;

/* --- struct ct_data_s --- */
struct ct_data_s {
	union {
		ush freq;
		ush code;
	} fc;
	union {
		ush dad;
		ush len;
	} dl;
};

/* --- typedef ct_data --- */
typedef struct ct_data_s ct_data;

/* --- typedef Pos --- */
typedef ush Pos;

/* --- typedef IPos --- */
typedef unsigned int IPos;

/* --- API function declarations --- */
const char *(zlibVersion(void));
const z_crc_t *(get_crc_table(void));
int deflateInit2_(z_streamp strm, int level, int method, int windowBits, int memLevel, int strategy, const char *version, int stream_size);
int deflate(z_streamp strm, int flush);
int deflateEnd(z_streamp strm);
int deflateReset(z_streamp strm);
int deflateParams(z_streamp strm, int level, int strategy);
int deflatePending(z_streamp strm, unsigned int *pending, int *bits);
int deflatePrime(z_streamp strm, int bits, int value);
int deflateSetDictionary(z_streamp strm, const Bytef *dictionary, uInt dictLength);
uLong crc32(long unsigned int crc, const unsigned char *buf, uInt len);
uLong adler32(uLong adler, const Bytef *buf, uInt len);
