/* Auto-generated by vkso-gen-types (safe funcs only). */
#pragma once
#include <stddef.h>
#include <stdint.h>

/* --- BTF source: vmlinux (/sys/kernel/btf/vmlinux) --- */
/* --- typedef __u32 --- */
typedef unsigned int __u32;

/* --- typedef u32 --- */
typedef __u32 u32;

/* --- typedef __kernel_ulong_t --- */
typedef long unsigned int __kernel_ulong_t;

/* --- typedef __kernel_size_t --- */
typedef __kernel_ulong_t __kernel_size_t;

/* --- typedef size_t --- */
typedef __kernel_size_t size_t;

/* --- typedef Byte --- */
typedef unsigned char Byte;

/* --- typedef uLong --- */
typedef long unsigned int uLong;

/* --- struct z_stream_s --- */
struct z_stream_s {
	const Byte *next_in;
	uLong avail_in;
	uLong total_in;
	Byte *next_out;
	uLong avail_out;
	uLong total_out;
	char *msg;
	struct internal_state *state;
	void *workspace;
	int data_type;
	uLong adler;
	uLong reserved;
};

/* --- struct internal_state --- */
struct internal_state {
	int dummy;
};

/* --- typedef z_stream --- */
typedef struct z_stream_s z_stream;

/* --- typedef z_streamp --- */
typedef z_stream *z_streamp;

/* --- API function declarations --- */
int mz_zlib_deflate(z_streamp strm, int flush);
int mz_zlib_deflateInit2(z_streamp strm, int level, int method, int windowBits, int memLevel, int strategy);
int mz_zlib_deflate_workspacesize(int windowBits, int memLevel);
int mz_zlib_deflateReset(z_streamp strm);
int mz_zlib_deflateEnd(z_streamp strm);
void mz_crc32init_le(void);
u32 mz_crc32(u32 crc, const unsigned char *p, size_t len);
const u32 *(mz_get_crc_table(void));
