/* Auto-generated by vkso-gen-types (safe funcs only). */
#pragma once
#include <stddef.h>
#include <stdint.h>

/* --- BTF source: vmlinux (/sys/kernel/btf/vmlinux) --- */
/* --- typedef Byte --- */
typedef unsigned char Byte;

/* --- typedef uLong --- */
typedef long unsigned int uLong;

/* --- struct z_stream_s --- */
struct z_stream_s {
	const Byte *next_in;
	uLong avail_in;
	uLong total_in;
	Byte *next_out;
	uLong avail_out;
	uLong total_out;
	char *msg;
	struct internal_state *state;
	void *workspace;
	int data_type;
	uLong adler;
	uLong reserved;
};

/* --- struct internal_state --- */
struct internal_state {
	int dummy;
};

/* --- typedef z_stream --- */
typedef struct z_stream_s z_stream;

/* --- typedef z_streamp --- */
typedef z_stream *z_streamp;

/* --- API function declarations --- */
int mz_zlib_deflate(z_streamp strm, int flush);
