/* Auto-generated by vkso-gen-types (safe funcs only). */
#pragma once
#include <stddef.h>
#include <stdint.h>

/* --- BTF source: vmlinux (/sys/kernel/btf/vmlinux) --- */
/* --- typedef __u32 --- */
typedef unsigned int __u32;

/* --- typedef u32 --- */
typedef __u32 u32;

/* --- typedef __kernel_ulong_t --- */
typedef long unsigned int __kernel_ulong_t;

/* --- typedef __kernel_size_t --- */
typedef __kernel_ulong_t __kernel_size_t;

/* --- typedef size_t --- */
typedef __kernel_size_t size_t;

/* --- typedef uint32_t --- */
typedef u32 uint32_t;

